# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: oxmirza@gmail.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://axm2.github.io"
name: Omar Mirza
job: Computer Science Student
location: Queens, New York
languages: C++, Java, Ruby, Python
twitter_username: no
github_username:  axm2
codepen_username:  no
email_address: oxmirza@gmail.com

# Build settings
markdown: kramdown
